version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=GoDbUser
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Go-test-db